name: Build and Deploy Docker Image

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Run the workflow on Ubuntu virtual machines

    steps:
      - uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Build Docker image
        run: docker build -t hello-world .  # Replace "hello-world" with your desired image name

      - name: Run the container locally
        run: docker run -p 5000:5000 hello-world  # Replace port mapping if needed
      - name: Check if app is running
        run: |
          nc -z localhost 5000
          if [[ $? -eq 0 ]]; then
            echo "App is running!"
          else
            echo "App is not running."
            exit 1  # Exit workflow with failure
          fi

      - name: Stop the container (if running)
        run: docker stop hello-world  # Stop the containe
